services:
  db:
    image: postgres:15-alpine
    container_name: qazaqair-db-1
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airmonitor
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: nginx:alpine
    container_name: qazaqair-app-1
    restart: always
    ports:
      - "80:80" # Changed from 8081 to 80 as it's the main app and monitoring moved
    networks:
      - app-network
      - monitoring_network

networks:
  app-network:
    driver: bridge
  monitoring_network:
    external: true
    name: monitoring_network
