# Lab 6: Data Sources
# Цель: Получение данных о существующих ресурсах
# Отличие: Если resource создает что-то новое, то data только запрашивает информацию

# =============================================================================
# DATA SOURCES - Получение информации о существующих ресурсах
# =============================================================================

# Получение информации о текущем аккаунте и регионе
data "aws_caller_identity" "current" {}

data "aws_region" "current" {}

# Data Source: Доступные Availability Zones
data "aws_availability_zones" "available" {
  state = "available"
}

# Data Source: Получение AMI (Amazon Linux 2023)
data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# Data Source: Получение Ubuntu AMI
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"]  # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# Data Source: Поиск VPC по тегу (предполагается что Lab 5 создала VPC с тегом Lab=lab5-vpc)
data "aws_vpcs" "lab5_vpcs" {
  filter {
    name   = "tag:Lab"
    values = ["lab5-vpc"]
  }
}

# Data Source: Получение подсетей найденного VPC
data "aws_subnets" "lab5_public" {
  filter {
    name   = "vpc-id"
    values = data.aws_vpcs.lab5_vpcs.ids
  }

  filter {
    name   = "tag:Type"
    values = ["public"]
  }
}

data "aws_subnets" "lab5_private" {
  filter {
    name   = "vpc-id"
    values = data.aws_vpcs.lab5_vpcs.ids
  }

  filter {
    name   = "tag:Type"
    values = ["private"]
  }
}

# Data Source: Получение Security Group по имени
data "aws_security_group" "web" {
  filter {
    name   = "group-name"
    values = ["lab5-web-sg"]
  }
}

# Data Source: Получение IAM политики (AWS managed)
data "aws_iam_policy" "read_only" {
  name = "ReadOnlyAccess"
}

# Data Source: Получение списка инстансов EC2
data "aws_instances" "lab5_web" {
  filter {
    name   = "tag:Lab"
    values = ["lab5-vpc"]
  }

  filter {
    name   = "instance-state-name"
    values = ["running"]
  }
}

# =============================================================================
# РЕСУРСЫ (создаем на основе данных из data sources)
# =============================================================================

# Создаем новый инстанс используя AMI из data source
resource "aws_instance" "new_server" {
  count = min(1, length(data.aws_subnets.lab5_public.ids))

  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  subnet_id              = tolist(data.aws_subnets.lab5_public.ids)[count.index]
  vpc_security_group_ids = [data.aws_security_group.web.id]

  tags = {
    Name        = "lab6-data-source-instance"
    Lab         = "lab6"
    SourceAMI   = data.aws_ami.ubuntu.name
    SourceOwner = data.aws_ami.ubuntu.owner_id
    CreatedIn   = data.aws_region.current.name
    AccountId   = data.aws_caller_identity.current.account_id
  }
}

# Создаем снимок (snapshot) информации о существующей инфраструктуре
resource "local_file" "infrastructure_report" {
  content = <<-EOF
    # Infrastructure Report Generated by Lab 6
    Generated at: ${timestamp()}

    ## Account Information
    - Account ID: ${data.aws_caller_identity.current.account_id}
    - Region: ${data.aws_region.current.name}

    ## Available AZs (${length(data.aws_availability_zones.available.names)})
    ${join("\n    ", [for az in data.aws_availability_zones.available.names : "- ${az}"])}

    ## AMIs Found
    - Amazon Linux: ${data.aws_ami.amazon_linux.id} (${data.aws_ami.amazon_linux.name})
    - Ubuntu: ${data.aws_ami.ubuntu.id} (${data.aws_ami.ubuntu.name})

    ## Existing Infrastructure (from Lab 5)
    - VPCs with tag Lab=lab5-vpc: ${join(", ", data.aws_vpcs.lab5_vpcs.ids)}
    - Public Subnets: ${join(", ", data.aws_subnets.lab5_public.ids)}
    - Private Subnets: ${join(", ", data.aws_subnets.lab5_private.ids)}
    - Security Group: ${data.aws_security_group.web.id}
    - Running EC2 instances: ${join(", ", data.aws_instances.lab5_web.ids)}

    ## AWS Managed Policy
    - ReadOnlyAccess ARN: ${data.aws_iam_policy.read_only.arn}
  EOF

  filename = "${path.module}/infrastructure_report.txt"
}
