# Ansible Inventory for QazaqAir Infrastructure
# Module 9: IaC - Infrastructure as Code

[local]
localhost ansible_connection=local

[docker_hosts]
localhost ansible_connection=local

[bastion]
localhost ansible_connection=local

[app_servers]
# Private EC2 instances (accessed via Bastion)
10.0.10.18 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[production]
# Terraform-created Bastion server
52.59.203.244 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
project_name=qazaqair
environment=production

[production:vars]
ansible_python_interpreter=/usr/bin/python3
environment=production

[bastion:vars]
ansible_python_interpreter=/usr/bin/python3
environment=production
